// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKSeY6KMUriRU3R5pcpXANJg3fGzOaijU',
    appId: '1:5493470272:android:82c5ef32c64b8989011ba5',
    messagingSenderId: '5493470272',
    projectId: 'check-presence-aa5d0',
    databaseURL: 'https://check-presence-aa5d0-default-rtdb.firebaseio.com',
    storageBucket: 'check-presence-aa5d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRmLzvZ8ywI1kHmV0rOeijjZ_Y9S3pBpE',
    appId: '1:5493470272:ios:73ab93d989243e46011ba5',
    messagingSenderId: '5493470272',
    projectId: 'check-presence-aa5d0',
    databaseURL: 'https://check-presence-aa5d0-default-rtdb.firebaseio.com',
    storageBucket: 'check-presence-aa5d0.firebasestorage.app',
    iosBundleId: 'com.example.checkPresence',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvmhR4TDNlrbjzGebr76-wRi7nJ52faEI',
    appId: '1:5493470272:web:d3214dcf7c84b423011ba5',
    messagingSenderId: '5493470272',
    projectId: 'check-presence-aa5d0',
    authDomain: 'check-presence-aa5d0.firebaseapp.com',
    databaseURL: 'https://check-presence-aa5d0-default-rtdb.firebaseio.com',
    storageBucket: 'check-presence-aa5d0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvmhR4TDNlrbjzGebr76-wRi7nJ52faEI',
    appId: '1:5493470272:web:23d471c78835ef55011ba5',
    messagingSenderId: '5493470272',
    projectId: 'check-presence-aa5d0',
    authDomain: 'check-presence-aa5d0.firebaseapp.com',
    databaseURL: 'https://check-presence-aa5d0-default-rtdb.firebaseio.com',
    storageBucket: 'check-presence-aa5d0.firebasestorage.app',
  );

}